###############################################################
- name: Update all packages to latest version
  apt:
    update_cache: yes

- name: Installing docker
  apt:
    name: "{{ item }}"
    state: installed 
  with_items:
    - docker

# to save docker file image, run:
# docker save -o <destination path> <image_name>

- name: Creates directory tor_service
  file:
    path: /tor_service/docker_image
    state: directory
#   owner: www-data
#   group: www-data
    mode: 0775
    recurse: yes

- name: Upload docker image
  copy:
    src: build/image.tar
    dest: /tor_service/docker_images/onion_django_app.tar
#   owner: www-data
#   group: www-data
#   mode: 0775

# path to tor should be variable
- name: Load docker image
  command: docker load -i /tor_service/docker_images/onion_django_app.tar

# this should be done using docker module
# there should be variable
- name: Run docker container 
  command: docker run -d -p 80:80 onion_django_app:latest